use_frameworks!

platform :ios, '9.0'

target 'ALComponentManager_Example' do
  pod 'ALComponentManager', :path => '../'

  target 'ALComponentManager_Tests' do
    inherit! :search_paths

    
  end
end
