use_frameworks!

platform :ios, '8.0'

target 'LMComponentManager_Example' do
  pod 'LMComponentManager', :path => '../'

  target 'LMComponentManager_Tests' do
    inherit! :search_paths

    
  end
end
